My Application: MyGraphics/Source/Application.cpp File Reference
Application.cpp File Reference
#include "Application.h"
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include "Scene1.h"
#include "Scene2.h"
#include "Scene3.h"
#include "Scene4.h"
#include "Assignment1.h"
#include "SceneLight.h"
#include "SceneLight2.h"
#include "Assignment2.h"
#include "SceneTexture.h"
#include "SceneSkybox.h"
#include "SceneModel.h"
#include "SceneText.h"
#include "Assignment3.h"
Functions
static void error_callback (int error, const char *description)
static void key_callback (GLFWwindow *window, int key, int scancode, int action, int mods)
static void mouseButtonCallback (GLFWwindow *m_window, int button, int action, int mods)
static void cursorEnterCallback (GLFWwindow *m_window, int entered)
void resize_callback (GLFWwindow *window, int w, int h)
Variables
GLFWwindow * m_window
const unsigned char FPS = 60
const unsigned int frameTime = 1000 / FPS
Function Documentation
static void cursorEnterCallback (GLFWwindow * m_window, int entered) static
Definition at line 75 of file Application.cpp.
Referenced by Application::Init().
static void error_callback (int error, const char * description) static
Definition at line 38 of file Application.cpp.
Referenced by Application::Init().
static void key_callback (GLFWwindow * window, int key, int scancode, int action, int mods) static
Definition at line 45 of file Application.cpp.
Referenced by Application::Init().
static void mouseButtonCallback (GLFWwindow * m_window, int button, int action, int mods) static
Definition at line 63 of file Application.cpp.
Referenced by Application::Init().
void resize_callback (GLFWwindow * window, int w, int h)
Definition at line 95 of file Application.cpp.
Referenced by Application::Init().
Variable Documentation
const unsigned char FPS = 60
Definition at line 34 of file Application.cpp.
const unsigned int frameTime = 1000 / FPS
Definition at line 35 of file Application.cpp.
Referenced by Application::Run().
GLFWwindow* m_window
Definition at line 33 of file Application.cpp.
Referenced by Application::Exit(), Application::Init(), Application::MouseMove(), and Application::Run().