My Application: MyGraphics/Source/Camera3.cpp File Reference
Camera3.cpp File Reference
#include "Camera3.h"
#include "Application.h"
#include "Mtx44.h"
#include <GLFW\glfw3.h>
#include <iostream>
Functions
bool bound (Vector3 &camPos)
bool planeHitbox (Vector3 &camPos)
bool chopperHitbox (Vector3 &camPos)
Function Documentation
bool bound (Vector3 & camPos)
Definition at line 30 of file Camera3.cpp.
References Vector3::x, and Vector3::z.
Referenced by Camera3::Update().
bool chopperHitbox (Vector3 & camPos)
Definition at line 60 of file Camera3.cpp.
References Vector3::x, and Vector3::z.
Referenced by Ass3::Render().
bool planeHitbox (Vector3 & camPos)
Definition at line 45 of file Camera3.cpp.
References Vector3::x, and Vector3::z.
Referenced by Ass3::Render(), and Ass3::Update().