My Application: MyGraphics/Source/Camera3.h File Reference
Camera3.h File Reference
#include "Camera.h"
Data Structures
class Camera3
Functions
bool planeHitbox (Vector3 &camPos)
bool chopperHitbox (Vector3 &camPos)
Function Documentation
bool chopperHitbox (Vector3 & camPos)
Definition at line 60 of file Camera3.cpp.
References Vector3::x, and Vector3::z.
Referenced by Ass3::Render().
bool planeHitbox (Vector3 & camPos)
Definition at line 45 of file Camera3.cpp.
References Vector3::x, and Vector3::z.
Referenced by Ass3::Render(), and Ass3::Update().