My Application: Ass3 Class Reference
Ass3 Class Reference
#include <Assignment3.h>
Public Member Functions
Ass3 ()
~Ass3 ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_CUBE = 0, GEO_AXES, GEO_GLASS, GEO_LIGHTBALL,
GEO_LEFT, GEO_RIGHT, GEO_TOP, GEO_BOTTOM,
GEO_FRONT, GEO_BACK, GEO_MODEL1, GEO_MODEL2,
GEO_TEXT, GEO_HOUSE1, GEO_HOUSE2, GEO_CAPE1,
GEO_CAPE2, GEO_CAPE3, GEO_CAPE4, GEO_NOSE,
GEO_MOUTH1, GEO_MOUTH2, GEO_HEAD, GEO_ARM1,
GEO_ARM2, GEO_ARM3, GEO_EYE1, GEO_EYE2,
GEO_HAT1, GEO_HAT2, GEO_CROSS, GEO_EAR,
GEO_HORN1, GEO_HORN2, GEO_BODY, GEO_PANT,
GEO_CANDY, GEO_STICK, GEO_TREE1, GEO_SWITCH,
NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderSkybox ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
float armRotate
float upperJump
float lowerJump
float inputDelay = 0.0f
bool checkArm
bool smile
bool jumping
bool togjump
bool board
Vector3 PlanePos
Camera3 camera
Light light [10]
MS modelStack
MS viewStack
MS projectionStack
Detailed Description
Definition at line 10 of file Assignment3.h.
Member Enumeration Documentation
enum Ass3::GEOMETRY_TYPE private
Enumerator
GEO_CUBE
GEO_AXES
GEO_GLASS
GEO_LIGHTBALL
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
GEO_MODEL1
GEO_MODEL2
GEO_TEXT
GEO_HOUSE1
GEO_HOUSE2
GEO_CAPE1
GEO_CAPE2
GEO_CAPE3
GEO_CAPE4
GEO_NOSE
GEO_MOUTH1
GEO_MOUTH2
GEO_HEAD
GEO_ARM1
GEO_ARM2
GEO_ARM3
GEO_EYE1
GEO_EYE2
GEO_HAT1
GEO_HAT2
GEO_CROSS
GEO_EAR
GEO_HORN1
GEO_HORN2
GEO_BODY
GEO_PANT
GEO_CANDY
GEO_STICK
GEO_TREE1
GEO_SWITCH
NUM_GEOMETRY
Definition at line 12 of file Assignment3.h.
enum Ass3::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 57 of file Assignment3.h.
Constructor & Destructor Documentation
Ass3::Ass3 ()
Definition at line 14 of file Assignment3.cpp.
Ass3::~Ass3 ()
Definition at line 18 of file Assignment3.cpp.
Member Function Documentation
void Ass3::Exit () virtual
Implements Scene.
Definition at line 1152 of file Assignment3.cpp.
References m_programID, and m_vertexArrayID.
void Ass3::Init () virtual
Implements Scene.
Definition at line 22 of file Assignment3.cpp.
References armRotate, board, camera, checkArm, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCircle(), MeshBuilder::GenerateCone(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateCylin(), MeshBuilder::GenerateHalfHemi(), MeshBuilder::GenerateHalfTorus(), MeshBuilder::GenerateHemi(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), MeshBuilder::GenerateTorus(), GEO_ARM1, GEO_ARM2, GEO_ARM3, GEO_AXES, GEO_BACK, GEO_BODY, GEO_BOTTOM, GEO_CANDY, GEO_CAPE1, GEO_CAPE2, GEO_CAPE3, GEO_CAPE4, GEO_CROSS, GEO_EAR, GEO_EYE1, GEO_EYE2, GEO_FRONT, GEO_GLASS, GEO_HAT1, GEO_HAT2, GEO_HEAD, GEO_HORN1, GEO_HORN2, GEO_HOUSE1, GEO_HOUSE2, GEO_LEFT, GEO_LIGHTBALL, GEO_MODEL1, GEO_MODEL2, GEO_MOUTH1, GEO_MOUTH2, GEO_NOSE, GEO_PANT, GEO_RIGHT, GEO_STICK, GEO_SWITCH, GEO_TEXT, GEO_TOP, GEO_TREE1, Camera3::Init(), inputDelay, jumping, Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, light, Light::LIGHT_DIRECTIONAL, MS::LoadMatrix(), LoadShaders(), LoadTGA(), lowerJump, m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, PlanePos, Light::position, Light::power, projectionStack, Component::Set(), Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), smile, Light::spotDirection, Mesh::textureID, togjump, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, and upperJump.
void Ass3::Render () virtual
Implements Scene.
Definition at line 486 of file Assignment3.cpp.
References armRotate, camera, chopperHitbox(), FPS, GEO_ARM1, GEO_ARM2, GEO_ARM3, GEO_BODY, GEO_CANDY, GEO_CAPE1, GEO_CAPE2, GEO_CAPE3, GEO_CAPE4, GEO_CROSS, GEO_EAR, GEO_EYE1, GEO_EYE2, GEO_GLASS, GEO_HAT1, GEO_HAT2, GEO_HEAD, GEO_HORN1, GEO_HORN2, GEO_HOUSE1, GEO_LIGHTBALL, GEO_MODEL1, GEO_MODEL2, GEO_MOUTH1, GEO_MOUTH2, GEO_NOSE, GEO_PANT, GEO_STICK, GEO_SWITCH, GEO_TEXT, GEO_TREE1, inputDelay, Application::IsKeyPressed(), jumping, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), lowerJump, m_parameters, meshList, modelStack, planeHitbox(), PlanePos, MS::PopMatrix(), Camera::position, Light::position, MS::PushMatrix(), RenderMesh(), RenderSkybox(), RenderText(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), smile, Light::spotDirection, Camera::target, togjump, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, upperJump, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void Ass3::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 441 of file Assignment3.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), and RenderSkybox().
void Ass3::RenderSkybox () private
Definition at line 1039 of file Assignment3.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void Ass3::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 1085 of file Assignment3.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void Ass3::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 1112 of file Assignment3.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void Ass3::Update (double dt) virtual
Implements Scene.
Definition at line 310 of file Assignment3.cpp.
References armRotate, board, camera, checkArm, Vector3::Cross(), Camera3::EnterShip(), FPS, inputDelay, Application::IsKeyPressed(), jumping, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, lowerJump, LSPEED, m_parameters, Vector3::Normalized(), planeHitbox(), PlanePos, Camera::position, Light::position, Camera3::right, smile, Camera::target, togjump, Light::type, U_LIGHT0_TYPE, Camera::up, Camera3::Update(), upperJump, Camera3::view, and Position::z.
Field Documentation
float Ass3::armRotate private
Definition at line 106 of file Assignment3.h.
Referenced by Init(), Render(), and Update().
bool Ass3::board private
Definition at line 114 of file Assignment3.h.
Referenced by Init(), and Update().
Camera3 Ass3::camera private
Definition at line 117 of file Assignment3.h.
Referenced by Init(), Render(), and Update().
bool Ass3::checkArm private
Definition at line 110 of file Assignment3.h.
Referenced by Init(), and Update().
float Ass3::inputDelay = 0.0f private
Definition at line 109 of file Assignment3.h.
Referenced by Init(), Render(), and Update().
bool Ass3::jumping private
Definition at line 112 of file Assignment3.h.
Referenced by Init(), Render(), and Update().
Light Ass3::light[10] private
Definition at line 118 of file Assignment3.h.
Referenced by Init(), Render(), and Update().
float Ass3::lowerJump private
Definition at line 108 of file Assignment3.h.
Referenced by Init(), Render(), and Update().
unsigned Ass3::m_parameters[U_TOTAL] private
Definition at line 104 of file Assignment3.h.
Referenced by Init(), Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), and Update().
unsigned Ass3::m_programID private
Definition at line 103 of file Assignment3.h.
Referenced by Exit(), and Init().
unsigned Ass3::m_vertexArrayID private
Definition at line 100 of file Assignment3.h.
Referenced by Exit(), and Init().
Mesh* Ass3::meshList[NUM_GEOMETRY] private
Definition at line 101 of file Assignment3.h.
Referenced by Init(), Render(), and RenderSkybox().
MS Ass3::modelStack private
Definition at line 120 of file Assignment3.h.
Referenced by Render(), RenderMesh(), RenderSkybox(), RenderText(), and RenderTextOnScreen().
Vector3 Ass3::PlanePos private
Definition at line 115 of file Assignment3.h.
Referenced by Init(), Render(), and Update().
MS Ass3::projectionStack private
Definition at line 120 of file Assignment3.h.
Referenced by Init(), RenderMesh(), RenderText(), and RenderTextOnScreen().
bool Ass3::smile private
Definition at line 111 of file Assignment3.h.
Referenced by Init(), Render(), and Update().
bool Ass3::togjump private
Definition at line 113 of file Assignment3.h.
Referenced by Init(), Render(), and Update().
float Ass3::upperJump private
Definition at line 107 of file Assignment3.h.
Referenced by Init(), Render(), and Update().
MS Ass3::viewStack private
Definition at line 120 of file Assignment3.h.
Referenced by Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
MyGraphics/Source/Assignment3.h
MyGraphics/Source/Assignment3.cpp