My Application: Ass2 Class Reference
Ass2 Class Reference
#include <Assignment2.h>
Public Member Functions
Ass2 ()
~Ass2 ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_CUBE = 0, GEO_AXES, GEO_GROUND, GEO_LIGHTBALL,
GEO_CAPE1, GEO_CAPE2, GEO_CAPE3, GEO_CAPE4,
GEO_NOSE, GEO_MOUTH1, GEO_MOUTH2, GEO_HEAD,
GEO_ARM1, GEO_ARM2, GEO_ARM3, GEO_EYE1,
GEO_EYE2, GEO_HAT1, GEO_HAT2, GEO_CROSS,
GEO_EAR, GEO_HORN1, GEO_HORN2, GEO_BODY,
GEO_PANT, GEO_TREE1, GEO_TREE2, GEO_CANDY,
GEO_STICK, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
float armRotate
float upperJump
float lowerJump
float inputDelay = 0.0f
bool checkArm
bool smile
bool jumping
bool togjump
Camera2 camera
Light light [10]
MS modelStack
MS viewStack
MS projectionStack
Detailed Description
Definition at line 10 of file Assignment2.h.
Member Enumeration Documentation
enum Ass2::GEOMETRY_TYPE private
Enumerator
GEO_CUBE
GEO_AXES
GEO_GROUND
GEO_LIGHTBALL
GEO_CAPE1
GEO_CAPE2
GEO_CAPE3
GEO_CAPE4
GEO_NOSE
GEO_MOUTH1
GEO_MOUTH2
GEO_HEAD
GEO_ARM1
GEO_ARM2
GEO_ARM3
GEO_EYE1
GEO_EYE2
GEO_HAT1
GEO_HAT2
GEO_CROSS
GEO_EAR
GEO_HORN1
GEO_HORN2
GEO_BODY
GEO_PANT
GEO_TREE1
GEO_TREE2
GEO_CANDY
GEO_STICK
NUM_GEOMETRY
Definition at line 12 of file Assignment2.h.
enum Ass2::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_TOTAL
Definition at line 47 of file Assignment2.h.
Constructor & Destructor Documentation
Ass2::Ass2 ()
Definition at line 11 of file Assignment2.cpp.
Ass2::~Ass2 ()
Definition at line 15 of file Assignment2.cpp.
Member Function Documentation
void Ass2::Exit () virtual
Implements Scene.
Definition at line 931 of file Assignment2.cpp.
References m_programID, and m_vertexArrayID.
void Ass2::Init () virtual
Implements Scene.
Definition at line 19 of file Assignment2.cpp.
References armRotate, camera, checkArm, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCircle(), MeshBuilder::GenerateCone(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateCylin(), MeshBuilder::GenerateHalfHemi(), MeshBuilder::GenerateHalfTorus(), MeshBuilder::GenerateHemi(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateTorus(), GEO_ARM1, GEO_ARM2, GEO_ARM3, GEO_AXES, GEO_BODY, GEO_CANDY, GEO_CAPE1, GEO_CAPE2, GEO_CAPE3, GEO_CAPE4, GEO_CROSS, GEO_EAR, GEO_EYE1, GEO_EYE2, GEO_GROUND, GEO_HAT1, GEO_HAT2, GEO_HEAD, GEO_HORN1, GEO_HORN2, GEO_LIGHTBALL, GEO_MOUTH1, GEO_MOUTH2, GEO_NOSE, GEO_PANT, GEO_STICK, GEO_TREE1, GEO_TREE2, Camera2::Init(), inputDelay, jumping, Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, light, Light::LIGHT_POINT, MS::LoadMatrix(), LoadShaders(), lowerJump, m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, Light::position, Light::power, projectionStack, Component::Set(), Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), smile, Light::spotDirection, togjump, Light::type, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, and upperJump.
void Ass2::Render () virtual
Implements Scene.
Definition at line 415 of file Assignment2.cpp.
References armRotate, camera, GEO_ARM1, GEO_ARM2, GEO_ARM3, GEO_AXES, GEO_BODY, GEO_CANDY, GEO_CAPE1, GEO_CAPE2, GEO_CAPE3, GEO_CAPE4, GEO_CROSS, GEO_EAR, GEO_EYE1, GEO_EYE2, GEO_GROUND, GEO_HAT1, GEO_HAT2, GEO_HEAD, GEO_HORN1, GEO_HORN2, GEO_LIGHTBALL, GEO_MOUTH1, GEO_MOUTH2, GEO_NOSE, GEO_PANT, GEO_STICK, GEO_TREE1, GEO_TREE2, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), lowerJump, m_parameters, meshList, modelStack, MS::PopMatrix(), Camera::position, Light::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), smile, Light::spotDirection, Camera::target, togjump, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, upperJump, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void Ass2::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 386 of file Assignment2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Application::IsKeyPressed(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), MS::Top(), U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render().
void Ass2::Update (double dt) virtual
Implements Scene.
Definition at line 270 of file Assignment2.cpp.
References armRotate, camera, checkArm, inputDelay, Application::IsKeyPressed(), jumping, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, lowerJump, LSPEED, m_parameters, Light::position, smile, togjump, Light::type, U_LIGHT0_TYPE, Camera2::Update(), upperJump, and Position::z.
Field Documentation
float Ass2::armRotate private
Definition at line 90 of file Assignment2.h.
Referenced by Init(), Render(), and Update().
Camera2 Ass2::camera private
Definition at line 99 of file Assignment2.h.
Referenced by Init(), Render(), and Update().
bool Ass2::checkArm private
Definition at line 94 of file Assignment2.h.
Referenced by Init(), and Update().
float Ass2::inputDelay = 0.0f private
Definition at line 93 of file Assignment2.h.
Referenced by Init(), and Update().
bool Ass2::jumping private
Definition at line 96 of file Assignment2.h.
Referenced by Init(), and Update().
Light Ass2::light[10] private
Definition at line 100 of file Assignment2.h.
Referenced by Init(), Render(), and Update().
float Ass2::lowerJump private
Definition at line 92 of file Assignment2.h.
Referenced by Init(), Render(), and Update().
unsigned Ass2::m_parameters[U_TOTAL] private
Definition at line 88 of file Assignment2.h.
Referenced by Init(), Render(), RenderMesh(), and Update().
unsigned Ass2::m_programID private
Definition at line 87 of file Assignment2.h.
Referenced by Exit(), and Init().
unsigned Ass2::m_vertexArrayID private
Definition at line 84 of file Assignment2.h.
Referenced by Exit(), and Init().
Mesh* Ass2::meshList[NUM_GEOMETRY] private
Definition at line 85 of file Assignment2.h.
Referenced by Init(), and Render().
MS Ass2::modelStack private
Definition at line 102 of file Assignment2.h.
Referenced by Render(), and RenderMesh().
MS Ass2::projectionStack private
Definition at line 102 of file Assignment2.h.
Referenced by Init(), and RenderMesh().
bool Ass2::smile private
Definition at line 95 of file Assignment2.h.
Referenced by Init(), Render(), and Update().
bool Ass2::togjump private
Definition at line 97 of file Assignment2.h.
Referenced by Init(), Render(), and Update().
float Ass2::upperJump private
Definition at line 91 of file Assignment2.h.
Referenced by Init(), Render(), and Update().
MS Ass2::viewStack private
Definition at line 102 of file Assignment2.h.
Referenced by Render(), and RenderMesh().
The documentation for this class was generated from the following files:
MyGraphics/Source/Assignment2.h
MyGraphics/Source/Assignment2.cpp