My Application: SceneLight2 Class Reference
SceneLight2 Class Reference
#include <SceneLight2.h>
Public Member Functions
SceneLight2 ()
~SceneLight2 ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_CUBE = 0, GEO_AXES, GEO_QUAD, GEO_CIRCLE,
GEO_RING, GEO_SPHERE, GEO_LIGHTBALL, GEO_CONE,
GEO_CYLIN, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
float rotateAngle
Camera2 camera
Light light [10]
MS modelStack
MS viewStack
MS projectionStack
Detailed Description
Definition at line 10 of file SceneLight2.h.
Member Enumeration Documentation
enum SceneLight2::GEOMETRY_TYPE private
Enumerator
GEO_CUBE
GEO_AXES
GEO_QUAD
GEO_CIRCLE
GEO_RING
GEO_SPHERE
GEO_LIGHTBALL
GEO_CONE
GEO_CYLIN
NUM_GEOMETRY
Definition at line 12 of file SceneLight2.h.
enum SceneLight2::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_TOTAL
Definition at line 26 of file SceneLight2.h.
Constructor & Destructor Documentation
SceneLight2::SceneLight2 ()
Definition at line 11 of file SceneLight2.cpp.
SceneLight2::~SceneLight2 ()
Definition at line 15 of file SceneLight2.cpp.
Member Function Documentation
void SceneLight2::Exit () virtual
Implements Scene.
Definition at line 261 of file SceneLight2.cpp.
References m_programID, and m_vertexArrayID.
void SceneLight2::Init () virtual
Implements Scene.
Definition at line 19 of file SceneLight2.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCone(), MeshBuilder::GenerateCylin(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), GEO_AXES, GEO_CONE, GEO_CYLIN, GEO_LIGHTBALL, GEO_QUAD, GEO_SPHERE, Camera2::Init(), Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, Light::position, Light::power, projectionStack, rotateAngle, Component::Set(), Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Light::type, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and U_NUMLIGHTS.
void SceneLight2::Render () virtual
Implements Scene.
Definition at line 199 of file SceneLight2.cpp.
References camera, GEO_AXES, GEO_CONE, GEO_LIGHTBALL, GEO_QUAD, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MS::PopMatrix(), Camera::position, Light::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Light::spotDirection, Camera::target, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneLight2::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 170 of file SceneLight2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), MS::Top(), U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render().
void SceneLight2::Update (double dt) virtual
Implements Scene.
Definition at line 131 of file SceneLight2.cpp.
References camera, Application::IsKeyPressed(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, LSPEED, m_parameters, Light::position, rotateAngle, Light::type, U_LIGHT0_TYPE, Camera2::Update(), and Position::z.
Field Documentation
Camera2 SceneLight2::camera private
Definition at line 70 of file SceneLight2.h.
Referenced by Init(), Render(), and Update().
Light SceneLight2::light[10] private
Definition at line 71 of file SceneLight2.h.
Referenced by Init(), Render(), and Update().
unsigned SceneLight2::m_parameters[U_TOTAL] private
Definition at line 66 of file SceneLight2.h.
Referenced by Init(), Render(), RenderMesh(), and Update().
unsigned SceneLight2::m_programID private
Definition at line 65 of file SceneLight2.h.
Referenced by Exit(), and Init().
unsigned SceneLight2::m_vertexArrayID private
Definition at line 62 of file SceneLight2.h.
Referenced by Exit(), and Init().
Mesh* SceneLight2::meshList[NUM_GEOMETRY] private
Definition at line 63 of file SceneLight2.h.
Referenced by Init(), and Render().
MS SceneLight2::modelStack private
Definition at line 73 of file SceneLight2.h.
Referenced by Render(), and RenderMesh().
MS SceneLight2::projectionStack private
Definition at line 73 of file SceneLight2.h.
Referenced by Init(), and RenderMesh().
float SceneLight2::rotateAngle private
Definition at line 68 of file SceneLight2.h.
Referenced by Init(), and Update().
MS SceneLight2::viewStack private
Definition at line 73 of file SceneLight2.h.
Referenced by Render(), and RenderMesh().
The documentation for this class was generated from the following files:
MyGraphics/Source/SceneLight2.h
MyGraphics/Source/SceneLight2.cpp