My Application: Camera3 Class Reference
Camera3 Class Reference
#include <Camera3.h>
Public Member Functions
Camera3 ()
~Camera3 ()
virtual void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
virtual void Update (double dt)
virtual void Reset ()
void EnterShip (Vector3 &planePos, double dt)
Public Member Functions inherited from Camera
Camera ()
~Camera ()
Data Fields
Vector3 defaultPosition
Vector3 defaultTarget
Vector3 defaultUp
Vector3 view
Vector3 right
Vector3 boundCheck
bool flying = false
bool jumping = false
bool togJump = false
float delay = 4.f
float jumpDelay = 9.f
double mousex
double mousey
Data Fields inherited from Camera
Vector3 position
Vector3 target
Vector3 up
Detailed Description
Definition at line 6 of file Camera3.h.
Constructor & Destructor Documentation
Camera3::Camera3 ()
Definition at line 11 of file Camera3.cpp.
Camera3::~Camera3 ()
Definition at line 15 of file Camera3.cpp.
Member Function Documentation
void Camera3::EnterShip (Vector3 & planePos, double dt)
Definition at line 75 of file Camera3.cpp.
References Application::MouseMove(), mousex, mousey, Camera::position, right, SCREEN_HEIGHT, SCREEN_WIDTH, Mtx44::SetToRotation(), Camera::target, Camera::up, view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Ass3::Update().
void Camera3::Init (const Vector3 & pos, const Vector3 & target, const Vector3 & up) virtual
Reimplemented from Camera.
Definition at line 19 of file Camera3.cpp.
References Vector3::Cross(), defaultPosition, defaultTarget, defaultUp, Vector3::Normalize(), Vector3::Normalized(), Camera::position, right, Camera::target, view, and Vector3::y.
Referenced by SceneSkybox::Init(), and Ass3::Init().
void Camera3::Reset () virtual
Reimplemented from Camera.
Definition at line 306 of file Camera3.cpp.
References defaultPosition, defaultTarget, defaultUp, Camera::position, Camera::target, and Camera::up.
Referenced by Update().
void Camera3::Update (double dt) virtual
Reimplemented from Camera.
Definition at line 105 of file Camera3.cpp.
References bound(), Vector3::Cross(), delay, flying, Application::IsKeyPressed(), jumpDelay, jumping, Application::MouseMove(), mousex, mousey, Vector3::Normalize(), Camera::position, Reset(), right, SCREEN_HEIGHT, SCREEN_WIDTH, Mtx44::SetToRotation(), Camera::target, togJump, Camera::up, view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SceneSkybox::Update(), and Ass3::Update().
Field Documentation
Vector3 Camera3::boundCheck
Definition at line 16 of file Camera3.h.
Vector3 Camera3::defaultPosition
Definition at line 9 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultTarget
Definition at line 10 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultUp
Definition at line 11 of file Camera3.h.
Referenced by Init(), and Reset().
float Camera3::delay = 4.f
Definition at line 21 of file Camera3.h.
Referenced by Update().
bool Camera3::flying = false
Definition at line 18 of file Camera3.h.
Referenced by Update().
float Camera3::jumpDelay = 9.f
Definition at line 22 of file Camera3.h.
Referenced by Update().
bool Camera3::jumping = false
Definition at line 19 of file Camera3.h.
Referenced by Update().
double Camera3::mousex
Definition at line 24 of file Camera3.h.
Referenced by EnterShip(), and Update().
double Camera3::mousey
Definition at line 24 of file Camera3.h.
Referenced by EnterShip(), and Update().
Vector3 Camera3::right
Definition at line 14 of file Camera3.h.
Referenced by EnterShip(), Init(), Update(), and Ass3::Update().
bool Camera3::togJump = false
Definition at line 20 of file Camera3.h.
Referenced by Update().
Vector3 Camera3::view
Definition at line 13 of file Camera3.h.
Referenced by EnterShip(), Init(), Update(), and Ass3::Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/Camera3.h
MyGraphics/Source/Camera3.cpp