My Application: Scene3 Class Reference
Scene3 Class Reference
#include <Scene3.h>
Public Member Functions
Scene3 ()
~Scene3 ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_CUBE = 0, GEO_QUAD, GEO_AXES, GEO_CIRCLE,
GEO_RING, GEO_SPHERE, GEO_HEMI, GEO_CYLIN,
NUM_GEOMETRY
}
enum UNIFORM_TYPE { U_MVP = 0, U_TOTAL }
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
float rotateAngle
Camera camera
Detailed Description
Definition at line 8 of file Scene3.h.
Member Enumeration Documentation
enum Scene3::GEOMETRY_TYPE private
Enumerator
GEO_CUBE
GEO_QUAD
GEO_AXES
GEO_CIRCLE
GEO_RING
GEO_SPHERE
GEO_HEMI
GEO_CYLIN
NUM_GEOMETRY
Definition at line 10 of file Scene3.h.
enum Scene3::UNIFORM_TYPE private
Enumerator
U_MVP
U_TOTAL
Definition at line 23 of file Scene3.h.
Constructor & Destructor Documentation
Scene3::Scene3 ()
Definition at line 10 of file Scene3.cpp.
Scene3::~Scene3 ()
Definition at line 14 of file Scene3.cpp.
Member Function Documentation
void Scene3::Exit () virtual
Implements Scene.
Definition at line 171 of file Scene3.cpp.
References m_programID, and m_vertexArrayID.
void Scene3::Init () virtual
Implements Scene.
Definition at line 18 of file Scene3.cpp.
References camera, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCircle(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateHemi(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateRing(), MeshBuilder::GenerateSphere(), GEO_AXES, GEO_CIRCLE, GEO_CUBE, GEO_HEMI, GEO_QUAD, GEO_RING, GEO_SPHERE, Camera::Init(), LoadShaders(), m_parameters, m_programID, m_vertexArrayID, meshList, rotateAngle, and U_MVP.
void Scene3::Render () virtual
Implements Scene.
Definition at line 80 of file Scene3.cpp.
References Mtx44::a, camera, GEO_AXES, GEO_HEMI, m_parameters, meshList, Camera::position, Mesh::Render(), rotateAngle, Mtx44::SetToIdentity(), Mtx44::SetToLookAt(), Mtx44::SetToPerspective(), Mtx44::SetToRotation(), Mtx44::SetToScale(), Mtx44::SetToTranslation(), Camera::target, U_MVP, Camera::up, Vector3::x, Vector3::y, and Vector3::z.
void Scene3::Update (double dt) virtual
Implements Scene.
Definition at line 64 of file Scene3.cpp.
References camera, Application::IsKeyPressed(), rotateAngle, and Camera::Update().
Field Documentation
Camera Scene3::camera private
Definition at line 46 of file Scene3.h.
Referenced by Init(), Render(), and Update().
unsigned Scene3::m_parameters[U_TOTAL] private
Definition at line 42 of file Scene3.h.
Referenced by Init(), and Render().
unsigned Scene3::m_programID private
Definition at line 41 of file Scene3.h.
Referenced by Exit(), and Init().
unsigned Scene3::m_vertexArrayID private
Definition at line 38 of file Scene3.h.
Referenced by Exit(), and Init().
Mesh* Scene3::meshList[NUM_GEOMETRY] private
Definition at line 39 of file Scene3.h.
Referenced by Init(), and Render().
float Scene3::rotateAngle private
Definition at line 44 of file Scene3.h.
Referenced by Init(), Render(), and Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/Scene3.h
MyGraphics/Source/Scene3.cpp