My Application: SceneModel Class Reference
SceneModel Class Reference
#include <SceneModel.h>
Public Member Functions
SceneModel ()
~SceneModel ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_CUBE = 0, GEO_AXES, GEO_QUAD, GEO_LIGHTBALL,
GEO_LEFT, GEO_RIGHT, GEO_TOP, GEO_BOTTOM,
GEO_FRONT, GEO_BACK, GEO_MODEL1, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderSkybox ()
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
float rotateAngle
Camera2 camera
Light light [10]
MS modelStack
MS viewStack
MS projectionStack
Detailed Description
Definition at line 10 of file SceneModel.h.
Member Enumeration Documentation
enum SceneModel::GEOMETRY_TYPE private
Enumerator
GEO_CUBE
GEO_AXES
GEO_QUAD
GEO_LIGHTBALL
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
GEO_MODEL1
NUM_GEOMETRY
Definition at line 12 of file SceneModel.h.
enum SceneModel::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TOTAL
Definition at line 28 of file SceneModel.h.
Constructor & Destructor Documentation
SceneModel::SceneModel ()
Definition at line 12 of file SceneModel.cpp.
SceneModel::~SceneModel ()
Definition at line 16 of file SceneModel.cpp.
Member Function Documentation
void SceneModel::Exit () virtual
Implements Scene.
Definition at line 316 of file SceneModel.cpp.
References m_programID, and m_vertexArrayID.
void SceneModel::Init () virtual
Implements Scene.
Definition at line 20 of file SceneModel.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_LIGHTBALL, GEO_MODEL1, GEO_QUAD, GEO_RIGHT, GEO_TOP, Camera2::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Light::power, projectionStack, rotateAngle, Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and U_NUMLIGHTS.
void SceneModel::Render () virtual
Implements Scene.
Definition at line 217 of file SceneModel.cpp.
References camera, GEO_LIGHTBALL, GEO_MODEL1, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MS::PopMatrix(), Camera::position, Light::position, MS::PushMatrix(), RenderMesh(), RenderSkybox(), MS::Scale(), Light::spotDirection, Camera::target, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneModel::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 172 of file SceneModel.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), and RenderSkybox().
void SceneModel::RenderSkybox () private
Definition at line 270 of file SceneModel.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneModel::Update (double dt) virtual
Implements Scene.
Definition at line 133 of file SceneModel.cpp.
References camera, Application::IsKeyPressed(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, LSPEED, m_parameters, Light::position, rotateAngle, Light::type, U_LIGHT0_TYPE, Camera2::Update(), and Position::z.
Field Documentation
Camera2 SceneModel::camera private
Definition at line 75 of file SceneModel.h.
Referenced by Init(), Render(), and Update().
Light SceneModel::light[10] private
Definition at line 76 of file SceneModel.h.
Referenced by Init(), Render(), and Update().
unsigned SceneModel::m_parameters[U_TOTAL] private
Definition at line 71 of file SceneModel.h.
Referenced by Init(), Render(), RenderMesh(), and Update().
unsigned SceneModel::m_programID private
Definition at line 70 of file SceneModel.h.
Referenced by Exit(), and Init().
unsigned SceneModel::m_vertexArrayID private
Definition at line 67 of file SceneModel.h.
Referenced by Exit(), and Init().
Mesh* SceneModel::meshList[NUM_GEOMETRY] private
Definition at line 68 of file SceneModel.h.
Referenced by Init(), Render(), and RenderSkybox().
MS SceneModel::modelStack private
Definition at line 78 of file SceneModel.h.
Referenced by Render(), RenderMesh(), and RenderSkybox().
MS SceneModel::projectionStack private
Definition at line 78 of file SceneModel.h.
Referenced by Init(), and RenderMesh().
float SceneModel::rotateAngle private
Definition at line 73 of file SceneModel.h.
Referenced by Init(), and Update().
MS SceneModel::viewStack private
Definition at line 78 of file SceneModel.h.
Referenced by Render(), and RenderMesh().
The documentation for this class was generated from the following files:
MyGraphics/Source/SceneModel.h
MyGraphics/Source/SceneModel.cpp