My Application: SceneText Class Reference
SceneText Class Reference
#include <SceneText.h>
Public Member Functions
SceneText ()
~SceneText ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_CUBE = 0, GEO_AXES, GEO_QUAD, GEO_LIGHTBALL,
GEO_LEFT, GEO_RIGHT, GEO_TOP, GEO_BOTTOM,
GEO_FRONT, GEO_BACK, GEO_MODEL1, GEO_TEXT,
NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderSkybox ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
float rotateAngle
Camera2 camera
Light light [10]
MS modelStack
MS viewStack
MS projectionStack
Detailed Description
Definition at line 10 of file SceneText.h.
Member Enumeration Documentation
enum SceneText::GEOMETRY_TYPE private
Enumerator
GEO_CUBE
GEO_AXES
GEO_QUAD
GEO_LIGHTBALL
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
GEO_MODEL1
GEO_TEXT
NUM_GEOMETRY
Definition at line 12 of file SceneText.h.
enum SceneText::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 29 of file SceneText.h.
Constructor & Destructor Documentation
SceneText::SceneText ()
Definition at line 12 of file SceneText.cpp.
SceneText::~SceneText ()
Definition at line 16 of file SceneText.cpp.
Member Function Documentation
void SceneText::Exit () virtual
Implements Scene.
Definition at line 394 of file SceneText.cpp.
References m_programID, and m_vertexArrayID.
void SceneText::Init () virtual
Implements Scene.
Definition at line 20 of file SceneText.cpp.
References camera, Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_LIGHTBALL, GEO_MODEL1, GEO_QUAD, GEO_RIGHT, GEO_TEXT, GEO_TOP, Camera2::Init(), Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Light::position, Light::power, projectionStack, rotateAngle, Position::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), Light::spotDirection, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, and U_TEXT_ENABLED.
void SceneText::Render () virtual
Implements Scene.
Definition at line 222 of file SceneText.cpp.
References camera, GEO_LIGHTBALL, GEO_MODEL1, GEO_TEXT, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MS::PopMatrix(), Camera::position, Light::position, MS::PushMatrix(), RenderMesh(), RenderSkybox(), RenderText(), RenderTextOnScreen(), MS::Scale(), Light::spotDirection, Camera::target, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneText::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 177 of file SceneText.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), and RenderSkybox().
void SceneText::RenderSkybox () private
Definition at line 281 of file SceneText.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SceneText::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 327 of file SceneText.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void SceneText::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 354 of file SceneText.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void SceneText::Update (double dt) virtual
Implements Scene.
Definition at line 138 of file SceneText.cpp.
References camera, Application::IsKeyPressed(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, LSPEED, m_parameters, Light::position, rotateAngle, Light::type, U_LIGHT0_TYPE, Camera2::Update(), and Position::z.
Field Documentation
Camera2 SceneText::camera private
Definition at line 81 of file SceneText.h.
Referenced by Init(), Render(), and Update().
Light SceneText::light[10] private
Definition at line 82 of file SceneText.h.
Referenced by Init(), Render(), and Update().
unsigned SceneText::m_parameters[U_TOTAL] private
Definition at line 77 of file SceneText.h.
Referenced by Init(), Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), and Update().
unsigned SceneText::m_programID private
Definition at line 76 of file SceneText.h.
Referenced by Exit(), and Init().
unsigned SceneText::m_vertexArrayID private
Definition at line 73 of file SceneText.h.
Referenced by Exit(), and Init().
Mesh* SceneText::meshList[NUM_GEOMETRY] private
Definition at line 74 of file SceneText.h.
Referenced by Init(), Render(), and RenderSkybox().
MS SceneText::modelStack private
Definition at line 84 of file SceneText.h.
Referenced by Render(), RenderMesh(), RenderSkybox(), RenderText(), and RenderTextOnScreen().
MS SceneText::projectionStack private
Definition at line 84 of file SceneText.h.
Referenced by Init(), RenderMesh(), RenderText(), and RenderTextOnScreen().
float SceneText::rotateAngle private
Definition at line 79 of file SceneText.h.
Referenced by Init(), and Update().
MS SceneText::viewStack private
Definition at line 84 of file SceneText.h.
Referenced by Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
MyGraphics/Source/SceneText.h
MyGraphics/Source/SceneText.cpp