My Application: SceneLight Class Reference
SceneLight Class Reference
#include <SceneLight.h>
Public Member Functions
SceneLight ()
~SceneLight ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_CUBE = 0, GEO_AXES, GEO_QUAD, GEO_CIRCLE,
GEO_RING, GEO_SPHERE, GEO_LIGHTBALL, GEO_CONE,
GEO_CYLIN, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
float rotateAngle
Camera2 camera
Light light [10]
MS modelStack
MS viewStack
MS projectionStack
Detailed Description
Definition at line 10 of file SceneLight.h.
Member Enumeration Documentation
enum SceneLight::GEOMETRY_TYPE private
Enumerator
GEO_CUBE
GEO_AXES
GEO_QUAD
GEO_CIRCLE
GEO_RING
GEO_SPHERE
GEO_LIGHTBALL
GEO_CONE
GEO_CYLIN
NUM_GEOMETRY
Definition at line 12 of file SceneLight.h.
enum SceneLight::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_TOTAL
Definition at line 26 of file SceneLight.h.
Constructor & Destructor Documentation
SceneLight::SceneLight ()
Definition at line 11 of file SceneLight.cpp.
SceneLight::~SceneLight ()
Definition at line 15 of file SceneLight.cpp.
Member Function Documentation
void SceneLight::Exit () virtual
Implements Scene.
Definition at line 197 of file SceneLight.cpp.
References m_programID, and m_vertexArrayID.
void SceneLight::Init () virtual
Implements Scene.
Definition at line 19 of file SceneLight.cpp.
References camera, Light::color, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCylin(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), GEO_AXES, GEO_CYLIN, GEO_LIGHTBALL, GEO_QUAD, GEO_SPHERE, Camera2::Init(), Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, light, MS::LoadMatrix(), LoadShaders(), m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, Light::position, Light::power, projectionStack, rotateAngle, Component::Set(), Position::Set(), Color::Set(), Mtx44::SetToPerspective(), U_LIGHT0_COLOR, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, and U_MVP.
void SceneLight::Render () virtual
Implements Scene.
Definition at line 161 of file SceneLight.cpp.
References camera, GEO_AXES, GEO_CYLIN, GEO_LIGHTBALL, GEO_QUAD, light, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MS::PopMatrix(), Camera::position, Light::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Camera::target, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SceneLight::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 132 of file SceneLight.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), MS::Top(), U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render().
void SceneLight::Update (double dt) virtual
Implements Scene.
Definition at line 103 of file SceneLight.cpp.
References camera, Application::IsKeyPressed(), light, LSPEED, Light::position, rotateAngle, Camera2::Update(), and Position::z.
Field Documentation
Camera2 SceneLight::camera private
Definition at line 64 of file SceneLight.h.
Referenced by Init(), Render(), and Update().
Light SceneLight::light[10] private
Definition at line 65 of file SceneLight.h.
Referenced by Init(), Render(), and Update().
unsigned SceneLight::m_parameters[U_TOTAL] private
Definition at line 60 of file SceneLight.h.
Referenced by Init(), Render(), and RenderMesh().
unsigned SceneLight::m_programID private
Definition at line 59 of file SceneLight.h.
Referenced by Exit(), and Init().
unsigned SceneLight::m_vertexArrayID private
Definition at line 56 of file SceneLight.h.
Referenced by Exit(), and Init().
Mesh* SceneLight::meshList[NUM_GEOMETRY] private
Definition at line 57 of file SceneLight.h.
Referenced by Init(), and Render().
MS SceneLight::modelStack private
Definition at line 67 of file SceneLight.h.
Referenced by Render(), and RenderMesh().
MS SceneLight::projectionStack private
Definition at line 67 of file SceneLight.h.
Referenced by Init(), and RenderMesh().
float SceneLight::rotateAngle private
Definition at line 62 of file SceneLight.h.
Referenced by Init(), and Update().
MS SceneLight::viewStack private
Definition at line 67 of file SceneLight.h.
Referenced by Render(), and RenderMesh().
The documentation for this class was generated from the following files:
MyGraphics/Source/SceneLight.h
MyGraphics/Source/SceneLight.cpp