My Application: Scene4 Class Reference
Scene4 Class Reference
#include <Scene4.h>
Public Member Functions
Scene4 ()
~Scene4 ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_CUBE = 0, GEO_AXES, GEO_QUAD, GEO_CIRCLE,
GEO_RING, GEO_SPHERE, GEO_SUN, NUM_GEOMETRY
}
enum UNIFORM_TYPE { U_MVP = 0, U_TOTAL }
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
float rotateAngle
Camera camera
MS modelStack
MS viewStack
MS projectionStack
Detailed Description
Definition at line 9 of file Scene4.h.
Member Enumeration Documentation
enum Scene4::GEOMETRY_TYPE private
Enumerator
GEO_CUBE
GEO_AXES
GEO_QUAD
GEO_CIRCLE
GEO_RING
GEO_SPHERE
GEO_SUN
NUM_GEOMETRY
Definition at line 11 of file Scene4.h.
enum Scene4::UNIFORM_TYPE private
Enumerator
U_MVP
U_TOTAL
Definition at line 23 of file Scene4.h.
Constructor & Destructor Documentation
Scene4::Scene4 ()
Definition at line 10 of file Scene4.cpp.
Scene4::~Scene4 ()
Definition at line 14 of file Scene4.cpp.
Member Function Documentation
void Scene4::Exit () virtual
Implements Scene.
Definition at line 153 of file Scene4.cpp.
References m_programID, and m_vertexArrayID.
void Scene4::Init () virtual
Implements Scene.
Definition at line 18 of file Scene4.cpp.
References camera, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateRing(), MeshBuilder::GenerateSphere(), GEO_AXES, GEO_CUBE, GEO_RING, GEO_SPHERE, GEO_SUN, Camera::Init(), MS::LoadMatrix(), LoadShaders(), m_parameters, m_programID, m_vertexArrayID, meshList, projectionStack, rotateAngle, Mtx44::SetToPerspective(), and U_MVP.
void Scene4::Render () virtual
Implements Scene.
Definition at line 81 of file Scene4.cpp.
References Mtx44::a, camera, GEO_AXES, GEO_RING, GEO_SPHERE, GEO_SUN, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MS::PopMatrix(), Camera::position, projectionStack, MS::PushMatrix(), Mesh::Render(), MS::Rotate(), rotateAngle, MS::Scale(), Camera::target, MS::Top(), MS::Translate(), U_MVP, Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void Scene4::Update (double dt) virtual
Implements Scene.
Definition at line 65 of file Scene4.cpp.
References camera, Application::IsKeyPressed(), rotateAngle, and Camera::Update().
Field Documentation
Camera Scene4::camera private
Definition at line 46 of file Scene4.h.
Referenced by Init(), Render(), and Update().
unsigned Scene4::m_parameters[U_TOTAL] private
Definition at line 42 of file Scene4.h.
Referenced by Init(), and Render().
unsigned Scene4::m_programID private
Definition at line 41 of file Scene4.h.
Referenced by Exit(), and Init().
unsigned Scene4::m_vertexArrayID private
Definition at line 38 of file Scene4.h.
Referenced by Exit(), and Init().
Mesh* Scene4::meshList[NUM_GEOMETRY] private
Definition at line 39 of file Scene4.h.
Referenced by Init(), and Render().
MS Scene4::modelStack private
Definition at line 48 of file Scene4.h.
Referenced by Render().
MS Scene4::projectionStack private
Definition at line 48 of file Scene4.h.
Referenced by Init(), and Render().
float Scene4::rotateAngle private
Definition at line 44 of file Scene4.h.
Referenced by Init(), Render(), and Update().
MS Scene4::viewStack private
Definition at line 48 of file Scene4.h.
Referenced by Render().
The documentation for this class was generated from the following files:
MyGraphics/Source/Scene4.h
MyGraphics/Source/Scene4.cpp