My Application: MeshBuilder Class Reference
MeshBuilder Class Reference
Provides methods to generate mesh of different shapes.
#include <MeshBuilder.h>
Static Public Member Functions
static Mesh * GenerateOBJ (const std::string &meshName, const std::string &file_path)
static Mesh * GenerateText (const std::string &meshName, unsigned numRow, unsigned numCol)
static Mesh * GenerateAxes (const std::string &meshName, float lengthX, float lengthY, float lengthZ)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateQuad (const std::string &meshName, Color color)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCube (const std::string &meshName, Color color)
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCircle (const std::string &meshName, Color color, unsigned numSlices)
static Mesh * GenerateRing (const std::string &meshName, Color color, float innerRadius, unsigned numSlices)
static Mesh * GenerateSphere (const std::string &meshName, Color color, unsigned numStacks, unsigned numSlices)
static Mesh * GenerateHemi (const std::string &meshName, Color color, unsigned numStacks, unsigned numSlices)
static Mesh * GenerateCylin (const std::string &meshName, Color color, unsigned numSlices)
static Mesh * GenerateCone (const std::string &meshName, Color color, unsigned numSlices)
static Mesh * GenerateTorus (const std::string &meshName, Color color, unsigned numSlices, unsigned numStacks, float innerRadius, float outerRadius)
static Mesh * GenerateHalfTorus (const std::string &meshName, Color color, unsigned numSlices, unsigned numStacks, float innerRadius, float outerRadius)
static Mesh * GenerateHalfHemi (const std::string &meshName, Color color, unsigned numStacks, unsigned numSlices)
Detailed Description
Provides methods to generate mesh of different shapes.
Class MeshBuilder:
Definition at line 15 of file MeshBuilder.h.
Member Function Documentation
Mesh * MeshBuilder::GenerateAxes (const std::string & meshName, float lengthX, float lengthY, float lengthZ) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - x-axis should start at -lengthX / 2 and end at lengthX / 2
lengthY - y-axis should start at -lengthY / 2 and end at lengthY / 2
lengthZ - z-axis should start at -lengthZ / 2 and end at lengthZ / 2
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 21 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), Color::Set(), and Mesh::vertexBuffer.
Referenced by Scene3::Init(), Scene4::Init(), SceneLight::Init(), SceneLight2::Init(), SceneTexture::Init(), SceneSkybox::Init(), SceneModel::Init(), SceneText::Init(), Ass2::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateCircle (const std::string & meshName, Color color, unsigned numSlices) static
Definition at line 190 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by Scene3::Init(), Ass2::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateCone (const std::string & meshName, Color color, unsigned numSlices) static
Definition at line 460 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vector3::Normalize(), Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by SceneLight2::Init(), Ass2::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateCube (const std::string & meshName, Color color) static
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of cube
lengthY - height of cube
lengthZ - depth of cube
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 114 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by Scene3::Init(), Scene4::Init(), Ass2::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateCylin (const std::string & meshName, Color color, unsigned numSlices) static
Definition at line 394 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vector3::Normalize(), Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by SceneLight::Init(), SceneLight2::Init(), Ass2::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateHalfHemi (const std::string & meshName, Color color, unsigned numStacks, unsigned numSlices) static
Definition at line 620 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), and Mesh::vertexBuffer.
Referenced by Ass2::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateHalfTorus (const std::string & meshName, Color color, unsigned numSlices, unsigned numStacks, float innerRadius, float outerRadius) static
Definition at line 569 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vector3::Normalized(), Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by Ass2::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateHemi (const std::string & meshName, Color color, unsigned numStacks, unsigned numSlices) static
Definition at line 331 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), and Mesh::vertexBuffer.
Referenced by Scene3::Init(), Ass2::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateOBJ (const std::string & meshName, const std::string & file_path) static
Definition at line 683 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, IndexVBO(), LoadOBJ(), Mesh::mode, and Mesh::vertexBuffer.
Referenced by SceneModel::Init(), SceneText::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateQuad (const std::string & meshName, Color color) static
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of quad
lengthY - height of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 67 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by Scene3::Init(), SceneLight::Init(), SceneLight2::Init(), SceneTexture::Init(), SceneSkybox::Init(), SceneModel::Init(), SceneText::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateRing (const std::string & meshName, Color color, float innerRadius, unsigned numSlices) static
Definition at line 231 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), and Mesh::vertexBuffer.
Referenced by Scene3::Init(), and Scene4::Init().
Mesh * MeshBuilder::GenerateSphere (const std::string & meshName, Color color, unsigned numStacks, unsigned numSlices) static
Definition at line 284 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), and Mesh::vertexBuffer.
Referenced by Scene3::Init(), Scene4::Init(), SceneLight::Init(), SceneLight2::Init(), SceneTexture::Init(), SceneSkybox::Init(), SceneModel::Init(), SceneText::Init(), Ass2::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateText (const std::string & meshName, unsigned numRow, unsigned numCol) static
Definition at line 709 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), TexCoord::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SceneText::Init(), and Ass3::Init().
Mesh * MeshBuilder::GenerateTorus (const std::string & meshName, Color color, unsigned numSlices, unsigned numStacks, float innerRadius, float outerRadius) static
Definition at line 518 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vector3::Normalized(), Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by Ass2::Init(), and Ass3::Init().
The documentation for this class was generated from the following files:
MyGraphics/Source/MeshBuilder.h
MyGraphics/Source/MeshBuilder.cpp